import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { PRIMARY, SECONDARY, seedAccount } from './accounts.ts';
import { readLocalSupabase, SupabaseNotRunning } from './localSupabase.ts';

const repoRoot = resolve(import.meta.dirname, '../../..');
const envPath = resolve(repoRoot, 'apps/web/.env.supabase');

try {
  const config = readLocalSupabase();
  const primary = await seedAccount(PRIMARY, config);
  await seedAccount(SECONDARY, config);

  writeFileSync(
    envPath,
    [
      '# Generated by `pnpm supabase:seed` — points the app at the local Supabase',
      '# stack. Values are the CLI development defaults, not credentials.',
      'VITE_IDENTITY_MODE=cloud',
      `VITE_SUPABASE_URL=${config.apiUrl}`,
      `VITE_SUPABASE_PUBLISHABLE_KEY=${config.publishableKey}`,
      'VITE_SYNC_MODE=supabase',
      '',
    ].join('\n'),
  );

  console.log(`wrote ${envPath.replace(repoRoot + '/', '')}`);
  console.log(`account ${primary.email} (${primary.id})`);
  console.log('');
  console.log('Start the app with:  nix develop -c pnpm dev:supabase');
  console.log('');
  console.log('Then in EACH browser window, sign in by pasting this into the console:');
  console.log('');
  console.log(signInSnippet(config.apiUrl, config.publishableKey));
  console.log('');
  console.log('Two windows on different origins (localhost and 127.0.0.1) act as two');
  console.log('devices — each gets its own local database but the same account.');
} catch (err) {
  if (err instanceof SupabaseNotRunning) {
    console.error(err.message);
    process.exit(1);
  }
  throw err;
}

/** `/@id/` is how Vite resolves a bare specifier for code pasted into the
 *  console, which has no module graph of its own. */
function signInSnippet(apiUrl: string, key: string): string {
  return [
    `const { createClient } = await import('/@id/@supabase/supabase-js');`,
    `await createClient('${apiUrl}', '${key}')`,
    `  .auth.signInWithPassword({ email: '${PRIMARY.email}', password: '${PRIMARY.password}' });`,
    `location.reload();`,
  ]
    .map((line) => `  ${line}`)
    .join('\n');
}
