// Database layer.
//
// Public surface: types + a comlink-wrapped client that talks to the DB
// worker. The worker owns the SQLite-WASM engine and OPFS persistence.

export type {
  CategoryCount,
  ColumnFilter,
  StringFilterMode,
  DatasetFileRef,
  DatasetRecord,
  DbStatus,
  EquipJobBucket,
  EquipJobCount,
  ExtractorResultRecord,
  EntityKind,
  EntitySummary,
  EquipRecord,
  GameDatabase,
  ItemRecord,
  LevelBandCount,
  ListOptsBase,
  MapMobRecord,
  MapMobSpawnRecord,
  MapMobSpawnWithName,
  MapMobWithName,
  MapNpcRecord,
  MapNpcWithName,
  MapPortalRecord,
  MapPortalWithName,
  MapRecord,
  MobDropRecord,
  MobDropWithName,
  MobRecord,
  NpcRecord,
  PageResult,
  QuestChainDetail,
  QuestChainEdgeRecord,
  QuestChainListRow,
  QuestChainMemberRecord,
  QuestChainMemberWithName,
  QuestChainRecord,
  QuestRecord,
  QuestRequirementRecord,
  QuestRequirementWithName,
  QuestRewardRecord,
  QuestRewardWithName,
  QuestSummary,
  SearchEntry,
  SortDir,
} from './types';
export {
  CURRENT_DATA_REVISION,
  MINIMUM_SUPPORTED_DATA_REVISION,
  evaluateDataState,
  type DataState,
} from './dataVersion';
export { getDbClient, terminateDbClient } from './client';
